### PR TITLE
Regen sample

### PR DESCRIPTION
**Pull request by SCedricThomas**
Update the sample-meteor to be more up-to-date and compatible with our new stack Scalingo-22.

### CODE REVIEW

**Comment by ipfaze** [comment]
As the meteor's repository: https://github.com/meteor/todos is deprecated and archived.
We decided to use the new repository: https://github.com/meteor/simple-todos-svelte as it is maintained and up to date.

Due to this changes, @Soulou can you have a look at it before we set this PR as reviewable?

**Comment by Soulou** [comment]
@ipfaze if it deploys well, LGTM

**Review by Soulou — APPROVED** [review]
@ipfaze if it deploys well, LGTM

**Comment by ipfaze** [comment]
> @ipfaze if it deploys well, LGTM

@Soulou, It deploys well but the interface is not the same as before.
You can have a look at the new one [here](https://med-sample.osc-fr1.scalingo.io/)

Is it still okay for you?

**Comment by Soulou** [comment]
100% ok

**Pull request merged**
